#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# run blockMesh to create the mesh
echo
echo "Running blockMesh"
echo
blockMesh > log.blockMesh

# make cell sets
echo
echo "Running setSet"
echo
setSet -batch makeCellSets.setSet > log.setSet

# make zones with the same name as sets
echo
echo "Running setsToZones"
echo
setsToZones -noFlipMap > log.setsToZones

# split mesh to different regions
echo
echo "Running splitMeshRegions"
echo
splitMeshRegions -cellZones -overwrite > log.splitMeshRegions

# remove fluid fields from solid regions (important for post-processing)
echo
echo "Removing fluid fields from solid regions"
echo
for i in Solid
do
    rm -f 0/$i/alpha1
    rm -f 0/$i/p_rgh
    rm -f 0/$i/rhoE
    rm -f 0/$i/U
done

echo
echo "Adjusting the dictionaries"
echo
# Adjust the dictionaries
for i in Solid Fluid
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

echo
echo "Running multiRegionSetFields"
echo
multiRegionSetFields -region Fluid > log.multiRegionSetFields

echo
echo "creating files for paraview post-processing"
echo
for i in Fluid Solid
do
   paraFoam -touch -region $i
done

# Temporary exit command
exit


# Decompose
for i in bottomAir topAir heater leftSolid rightSolid
do
   decomposePar -region $i > log.decomposePar.$i 2>&1
done

# Run
runParallel `getApplication` 4

# Reconstruct
for i in bottomAir topAir heater leftSolid rightSolid
do
   reconstructPar -region $i > log.reconstructPar.$i2 >&1
done

# ----------------------------------------------------------------- end-of-file

