#!/bin/bash

# Clean up
echo "Setting up initial directories and removing logs..."
rm -f log.*
rm -rf ?.[0-9] [0-9] [0-9][0-9]
if [ -d 0.org ]; 
then
    cp -r 0.org 0;
else
    echo "No 0.org directory found. Aborting.\n"
    exit 1
fi

if [ -d sets ];
then
    rm -rf sets;
fi
